
[[constraint]]
  branch = "master"
  name = "github.com/zoumo/register"

[[constraint]]
  branch = "master"
  name = "github.com/zoumo/logdog"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "^1.19.1"

[[override]]
  name = "k8s.io/client-go"
  version = "v3.0.0-beta.0"

