apiVersion: net.alpha.caicloud.io/v1alpha1
kind: LoadBalancer
metadata:
  name: "lb"
  namespace: "kube-system"
spec:
  # internal or external, can't convert each other
  type: "external"

  nodes:
    replicas: 3
    dedicated: PreferNoSchedule
    names:
    - kube-node-85

  # actually proxy is an ingress controller
  proxy: 
    type: nginx
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi

  # internal can only use service provider
  # external can use all kind of providers
  providers:
    service:
      name: xxxx
    ipvsdr:
      vip: 192.168.99.200
      scheduler: rr

